server:
  port: 11000

spring:
  application:
    name: consultareceita
  data:
    rest:
      base-path: "/v1"

logging:
  file: "${desafio.log.dir}/${spring.application.name}.log"
  level:
    root: INFO
    org.springframework.web: ${logging.level.root}
    logging.level.org.hibernate: ${logging.level.root}
aft.log.dir: "."

fsj:
  cnpj-api:
    url: https://receitaws.com.br/v1/cnpj

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    diskspace:
      enabled: false
